### ISSUE TITLE
Eastron SDM72D-v2 USB - RS485 Verbindung

### ISSUE THREAD

**Issue by romgen** [christian1980nrw/VenusOS-SDM72D-M-V2-Eastron-Modbus-driver#2]
Hallo!

Vielen Dank für die Änderungen im Code!
Kurze Nachfrage: Wie du hast du den SDM72D-v2 denn angeschlossen am RS485-USB-Adapter? Hast du die Data+- oder B+-Signale genommen? Hast du vielleicht ein Foto davon oder eine Zeichnung?
Bei mir wird der Eastron SDM72D-v2 nämlich nicht erkannt, trotz der Dateien.  Ich habe übrigens die Data+/- genommen und die beim USB an Orange und Gelb und Braun (GND) angeschlossen.

Vielen Dank!

**Comment by butterwecksolutions** [comment]
Hallo, das ist falsch. GND muss nicht angeschlossen werden, nur A+B auf beiden Seiten. Außerdem muss die Baudrate am Zähler konfiguriert werden, Passwort ist in meiner Beschreibung. Gruß Christian

**Comment by butterwecksolutions** [comment]
.
